name: flutter_hsc
description: A simple wather app.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  dartz: ^0.10.1
  intl: ^0.17.0
  json_annotation: any
  mobx: ^2.0.7
  flutter_mobx: ^2.0.6+1
  http: ^0.13.4
  shared_preferences: ^2.0.15
  mockito: ^5.2.0
  get_it: ^7.2.0
  dio: ^4.0.6
  flutter_secure_storage: ^5.0.2
  url_launcher: ^6.1.2
  google_fonts: ^2.3.1
  syncfusion_flutter_charts: ^20.1.57


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  json_serializable: any
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7

flutter:
  generate: true
  uses-material-design: true
